<link rel="stylesheet" href="./styles.css/styles.css">

<nav class="nav">
    <ul class="nav-content">
      <li class="nav-list">
        <a href="../../index.php" class="link-item lighted">
          <i class='bx bx-home link-icon'></i>
          <span class="link-text">Home</span>
        </a>
      </li>
      <li class="nav-list">
        <a href="../../jobs.php" class="link-item" id="jobs-menu">
          <i class='bx bxs-briefcase link-icon'></i>
          <span class="link-text">Jobs</span>
        </a>
      </li>


      <li class="nav-list">
        <a href="../../apply.php" class="link-item">
          <i class='bx bxs-registered link-icon'></i>
          <span class="link-text">Apply</span>
        </a>
      </li>
      <li class="nav-list">
        <a href="mailto:105710430@student.swin.edu.au" class="link-item">
          <i class='bx bxs-contact link-icon'></i>
          <span class="link-text">Contact</span>
        </a>
      </li>
      <li class="nav-list">
        <a href="../../tips.html" class="link-item">
          <i class='bx bxs-select-multiple link-icon'></i>
          <span class="link-text">Tips</span>
        </a>
      </li>
      <li class="nav-list">
        <a href="about.php" class="link-item">
          <i class='bx bx-meh-blank link-icon'></i>
          <span class="link-text">About</span>
        </a>
      </li>
      <li class="nav-list">
        <a href="../../enhancements.php" class="link-item">
          <i class='bx bx-up-arrow-alt link-icon'></i>
          <span class="link-text">Enhancements</span>
        </a>
      </li>

      <span class="indicator"></span>
    </ul>
  </nav>